# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SNMP-Info
version:      2.01
version_from: Info.pm
installdirs:  site
requires:
    Math::BigInt:                  0
    SNMP:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
