--- #YAML:1.0
name:               SNMP-Info
version:            2.11
abstract:           Object Oriented Perl5 Interface to Network devices and MIBs through SNMP. 
author:
    - Eric A. Miller <emiller@cpan.org>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::BigInt:  0
    SNMP:          0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
